apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secret
  namespace: default

type: Opaque
stringData:
  POSTGRES_USER: "castor_user"
  POSTGRES_PASSWORD: "Castor2025*"

  ORACLE_USER: "CASTOR_BILLING"
  ORACLE_PASSWORD: "Castor2025*"
