apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: default
  labels:
    app: billing-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service

  template:
    metadata:
      labels:
        app: billing-service

    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          imagePullPolicy: Never   # IMPORTANTE: para k3d o kind

          ports:
            - containerPort: 8081

          env:
            # Variables NO sensibles (ConfigMap)
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: POSTGRES_PORT

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: POSTGRES_DB

            - name: ORACLE_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: ORACLE_HOST

            - name: ORACLE_PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: ORACLE_PORT

            - name: ORACLE_PDB
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: ORACLE_PDB

            - name: PYTHON_CALCULATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: billing-service-config
                  key: PYTHON_CALCULATOR_URL

            # Variables sensibles (Secret)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-service-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-service-secret
                  key: POSTGRES_PASSWORD

            - name: ORACLE_USER
              valueFrom:
                secretKeyRef:
                  name: billing-service-secret
                  key: ORACLE_USER

            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-service-secret
                  key: ORACLE_PASSWORD
