apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData:

  # ðŸ”¹ Superusuario PostgreSQL
  POSTGRES_ROOT_PASSWORD: "Castor2025"

  # ðŸ”¹ Usuario de aplicaciÃ³n PostgreSQL
  POSTGRES_APP_USER: "castor_user"
  POSTGRES_APP_PASSWORD: "Castor2025"

  # ðŸ”¹ Usuario de aplicaciÃ³n Oracle
  ORACLE_USER: "CASTOR_BILLING"
  ORACLE_PASSWORD: "Castor2025"
