spring:
  application:
    name: billing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # MÃ¡s flexible para K8s
    # active: dev
server:
  port: 8081

logging:
  level:
    root: INFO

castor:
  billing:
    module-enabled: true