server:
  port: 8081

spring:
  application:
    name: billing-service

  datasource:
    primary:
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver

    oracle:
      url: jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_PDB}
      username: ${ORACLE_USER}
      password: ${ORACLE_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    root: INFO

castor:
  billing:
    module-enabled: true

  db:
    postgres:
      name: ${POSTGRES_DB}
    oracle:
      pdb: ${ORACLE_PDB}

external-services:
  invoice-calculator:
    url: ${PYTHON_CALCULATOR_URL:http://invoice-calculator:5001/calculate}
